micronaut:
  application:
    name: btcproxyd
  http:
    client:
      read-timeout: 300s
  ssl:
    enabled: false
    buildSelfSigned: false

btcproxyd:
  rpcproxy:
    network-id: org.bitcoin.production
    uri: http://localhost:8332
    username: rpcusername
    password: rpcpassword
    use-zmq: false
    allow-list:
      - getblockcount
      - getbestblockhash
      - getblock
      - getblockchaininfo
      - getblockcount
      - getblockhash
      - getblockheader
      - getblockstats
      - getchaintips
      - getchaintxstats
      - getdifficulty
      - gettxout
      - gettxoutproof
      - verifytxoutproof
      - getmemoryinfo
      - getrpcinfo
      - uptime
      - getconnectioncount
      - getnettotals
      - getnetworkinfo

