micronaut:
  http:
    client:
      read-timeout: 600s

btcproxyd:
  rpcproxy:
    network-id: org.bitcoin.regtest
    uri: http://localhost:18443
    username: setmeplease
    password: setmetooplease
    use-zmq: true
    allow-list:
      - getblockcount
      - getchaintips
      - getbestblockhash
      - getblockchaininfo
      - omniproxy.getrichlist
      - omniproxy.listproperties
      - omniproxy.getproperty

omniproxyd:
  enabled: true
